import Head from "next/head";
import { Inter } from "next/font/google";
import Soldiers from "./soldiers";
import { getTranslation } from "@/locales/TranslationHelper";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const t = getTranslation()

  return (
    <>
      <Head>
        <title>{t.logo}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Soldiers />
      </main>
    </>
  );
}
