import Head from "next/head";
import { Inter } from "next/font/google";
import Soldiers from "./soldiers";
import { getTranslation } from "@/locales/TranslationHelper";
import { getUserRole } from "@/helper/helper";
import Workers from "./workers";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const t = getTranslation()
  const role = getUserRole()
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
      setDomLoaded(true);
    }, []);

  return (
    <>
      <Head>
        <title>{t.logo}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {domLoaded &&
          <div>
            {role == 'ROLE_WORKER' && <Soldiers />}
            {role == 'ROLE_ADMIN' && <Workers />}
          </div>
        }
      </main>
    </>
  );
}
