// package feature_soldiers;

import com.ftn.sbnz.model.feature_soldiers.models.Soldier;
import com.ftn.sbnz.model.feature_soldiers.models.WarDuty;
import com.ftn.sbnz.model.feature_soldiers.values.WarDutyType;
import com.ftn.sbnz.model.feature_soldiers.values.SoldierCategory;
import java.time.Duration;
import java.time.temporal.ChronoUnit;

rule "Calculate months for classification"
    when 
        $soldier: Soldier($soldierId: id, SoldierCategory.UNCATEGORIZED == category, months == null)
        $totalDays: Number() from accumulate(
            WarDuty(
                soldier.id == $soldierId, 
                type == WarDutyType.WAR_ZONE, 
                $startDate: startDate, 
                $endDate: endDate
            ),
            sum((int)(ChronoUnit.DAYS.between($startDate, $endDate) + 1))
        )
    then 
        System.err.println($totalDays);
        modify($soldier) {setMonths((int) $totalDays/30);}
end