// package backward;

import com.ftn.sbnz.model.feature_soldiers.models.Unit;
import com.ftn.sbnz.model.feature_soldiers.models.Soldier;
import com.ftn.sbnz.model.core.Trigger;
import java.util.List;

query isContainedIn( String x, String y )
    Unit( x, y; )
    or
    ( Unit( z, y; ) and isContainedIn( x, z; ) )
end

global List<Soldier> soldiersInUnit;

rule "Get soldiers in Unit"
    agenda-group "units"
    when 
        Trigger($sp: searchParam)
        isContainedIn(id, $sp;)
        $s: Soldier(jmbg == id)
    then
        if (!soldiersInUnit.contains($s)) {
            soldiersInUnit.add($s);
        }
end